# Generated by Django 5.0.3 on 2024-07-30 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studentrecords',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='name', max_length=255, null=True)),
                ('age', models.IntegerField(blank=True, db_column='age', null=True)),
                ('gradesection', models.CharField(blank=True, db_column='gradesection', max_length=50, null=True)),
                ('date', models.DateField(blank=True, db_column='date', null=True)),
                ('gradelevel', models.CharField(blank=True, db_column='gradelevel', max_length=50, null=True)),
                ('assessment', models.CharField(blank=True, db_column='assessment', max_length=255, null=True)),
                ('total_miscues', models.IntegerField(blank=True, db_column='total_miscues', default=0, null=True)),
                ('oral_reading_score', models.IntegerField(blank=True, db_column='oral_reading_score', default=0, null=True)),
                ('reading_level', models.CharField(blank=True, db_column='reading_level', default=0, max_length=255, null=True)),
                ('post_total_miscues', models.IntegerField(blank=True, db_column='post_total_miscues', default=0, null=True)),
                ('post_oral_reading_score', models.IntegerField(blank=True, db_column='post_oral_reading_score', default=0, null=True)),
                ('post_reading_level', models.CharField(blank=True, db_column='post_reading_level', default=0, max_length=255, null=True)),
            ],
            options={
                'db_table': 'studentrecords',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teacherrecords',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'teacherrecords',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PostTestPassage',
            fields=[
                ('posttest_passage_id', models.AutoField(primary_key=True, serialize=False)),
                ('posttest_grade_level', models.IntegerField()),
                ('posttest_passage_title', models.TextField()),
                ('posttest_passage', models.TextField()),
                ('posttest_passage_prompt', models.TextField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostTestQuestions',
            fields=[
                ('posttest_questions_id', models.AutoField(primary_key=True, serialize=False)),
                ('posttest_grade_level', models.IntegerField()),
                ('posttest_question', models.TextField()),
                ('posttest_passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.posttestpassage')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostTestAnswers',
            fields=[
                ('posttest_answers_id', models.AutoField(primary_key=True, serialize=False)),
                ('posttest_grade_level', models.IntegerField()),
                ('posttest_answer', models.TextField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('posttest_passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.posttestpassage')),
                ('posttest_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.posttestquestions')),
            ],
        ),
        migrations.CreateModel(
            name='PreTestPassage',
            fields=[
                ('pretest_passage_id', models.AutoField(primary_key=True, serialize=False)),
                ('pretest_grade_level', models.IntegerField()),
                ('pretest_passage_title', models.TextField()),
                ('pretest_passage', models.TextField()),
                ('pretest_passage_prompt', models.TextField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreTestQuestions',
            fields=[
                ('pretest_questions_id', models.AutoField(primary_key=True, serialize=False)),
                ('pretest_grade_level', models.IntegerField()),
                ('pretest_question', models.TextField()),
                ('pretest_passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.pretestpassage')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreTestAnswers',
            fields=[
                ('pretest_answers_id', models.AutoField(primary_key=True, serialize=False)),
                ('pretest_grade_level', models.IntegerField()),
                ('pretest_answer', models.TextField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pretest_passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.pretestpassage')),
                ('pretest_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.pretestquestions')),
            ],
            options={
                'unique_together': {('pretest_question', 'pretest_answer', 'teacher')},
            },
        ),
    ]
